export const COLLECTIONS = {
  USERS: 'users',
  STUDENTS: 'students',
  TEACHERS: 'teachers',
  CLASSES: 'classes',
  UNITS: 'units',
  ATTENDANCE: 'attendance',
  EXAMS: 'exams',
  RESULTS: 'results',
  FEES: 'fees',
  PAYMENTS: 'payments',
  NOTIFICATIONS: 'notifications',
  CHATS: 'chats',
  MESSAGES: 'messages',
  SCHOOLS: 'schools',
  SETTINGS: 'settings',
  AUDIT_LOGS: 'auditLogs',
  TRANSCRIPTS: 'transcripts',
  HR: 'hr',
  ACADEMIC_YEARS: 'academicYears',
  SEMESTERS: 'semesters',
  DEPARTMENTS: 'departments',
  COURSES: 'courses',
  CLASSROOMS: 'classrooms',
  GRADUATION: 'graduation',
  ADMISSIONS: 'admissions',
  STUDENT_DOCUMENTS: 'studentDocuments',
  ATTACHMENTS: 'attachments',
  ALUMNI: 'alumni',
  CLEARANCES: 'clearances',
  CERTIFICATES: 'certificates',
  STUDENT_TIMELINE: 'studentTimeline',
  INVOICES: 'invoices',
  EXPENSES: 'expenses',
  BUDGETS: 'budgets',
  CREDIT_DEBIT_NOTES: 'creditDebitNotes',
  SCHOLARSHIPS: 'scholarships',
  INSTALLMENT_PLANS: 'installmentPlans',
  STUDENT_ACCOUNTS: 'studentAccounts',
} as const;

export type CollectionName = typeof COLLECTIONS[keyof typeof COLLECTIONS];
